// <auto-generated />
using EF_Code_First_Approach.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCodeFirstApproach.Migrations
{
    [DbContext(typeof(EF_Code_First_ApproachContext))]
    partial class EFCodeFirstApproachContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Code_First_Approach.Models.Mobile", b =>
                {
                    b.Property<int>("MobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MobID"));

                    b.Property<string>("MobBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MobPrice")
                        .HasColumnType("int");

                    b.HasKey("MobID");

                    b.ToTable("Mobile");
                });
#pragma warning restore 612, 618
        }
    }
}
